version: '3.3'

services:
  postgresql:
    image: postgres:16.4-alpine
    hostname: postgresql
    container_name: postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=5432
    volumes:
      - postgresql:/data/postgres

volumes:
  postgresql:
