spring:
  application:
    name: wordbuch

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_CURRENT_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      pool-name: wordbuch-hikari-pool
      schema: ${DB_CURRENT_SCHEMA}

  flyway:
    baseline-on-migrate: true
    schemas: ${DB_CURRENT_SCHEMA}

  devtools:
    livereload:
      enabled: false
